### PR TITLE
Bundle Update on 2018-01-05

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [devise](https://github.com/plataformatec/devise), [4.3.0...4.4.0](https://github.com/plataformatec/devise/compare/v4.3.0...v4.4.0) ([CHANGELOG](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md))
- Updated: [minitest](https://github.com/seattlerb/minitest), 5.10.3...5.11.1 ([CHANGELOG](https://github.com/seattlerb/minitest/blob/master/History.rdoc))
- Updated: [rspec-core](http://github.com/rspec/rspec-core), [3.7.0...3.7.1](https://github.com/rspec/rspec-core/compare/v3.7.0...v3.7.1) ([CHANGELOG](https://github.com/rspec/rspec-core/blob/master/Changelog.md))
- Updated: [uglifier](http://github.com/lautis/uglifier), [4.0.2...4.1.2](https://github.com/lautis/uglifier/compare/v4.0.2...v4.1.2) ([CHANGELOG](https://github.com/lautis/uglifier/blob/master/CHANGELOG.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
3 Pull Requests sent and 2 minutes, and 15 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by irisfaraway** [comment]
Looks like the Devise upgrade is to blame for the failing tests. Looking into it.

**Comment by irisfaraway** [comment]
Believe this is to do with Devise now clashing with our own password validation rules: https://github.com/plataformatec/devise/issues/4742

**Comment by irisfaraway** [comment]
I decided to stick with Devise 4.3.0 until more information is available about the issue.

**Comment by Cruikshanks** [comment]
Restarted the stalled Travis build but other than that will leave this to you to decide when to merge in.

The conclusion of the issue seems to be that it's not a Devise issue, but that folks models were in an invalid state hence no redirect. Are you ok to create an issue in this repo to come back and look at upgrading Devise, and trying to track down why we can't?

N.B. Side note [woodpigeon](https://github.com/woodpigeon) worked on WEX and replaced me as the lead for FRAE! Lovely person to work with and awesome Ruby dev 😄

**Comment by irisfaraway** [comment]
@Cruikshanks Yeah, I think fixing it will involve changing how we handle our password validations – which seems fine, just thought I'd wait to see what comes of the issue as people are still commenting on it. I'm happy to log an issue on our repo as well. But for now I'd rather get the rest of the bundle changes merged in.

And I thought I recognised that username :)

**Comment by irisfaraway** [comment]
Issue logged. I'm gonna go ahead and merge this in so we can have no open PRs for the first time in, like, ever.

**Pull request merged**
